// Lista de produtos
const produtos = [
    {
        id: 1,
        nome: "Nike Air Force 1 Branco",
        imagem: "Imagens/Produtos/1.png",
        precoDolar: 160,
        marca: "Nike",
        cor: "Branco",
        desc: "Um clássico atemporal da Nike, o Air Force 1 Branco combina estilo e conforto. Seu design limpo e solado robusto garantem durabilidade e versatilidade para qualquer ocasião.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 2,
        nome: "Jordan 4 Purple Metalic",
        imagem: "Imagens/Produtos/2.png",
        precoDolar: 380,
        marca: "Jordan",
        cor: "Branco e Roxo",
        desc: "Com um visual marcante, o Jordan 4 Purple Metallic traz detalhes roxos metálicos sobre a base branca, unindo luxo e esportividade em um modelo icônico da linha Air Jordan.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 3,
        nome: "Nike Dunk Low Ben & Jerry's",
        imagem: "Imagens/Produtos/3.png",
        precoDolar: 4700,
        marca: "Nike",
        cor: "Colorido",
        desc: "Inspirado no famoso sorvete da Ben & Jerry’s, este Nike Dunk é uma peça de colecionador com cores vibrantes e materiais premium que chamam atenção em qualquer lugar.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 4,
        nome: "Air Jordan 1 High OG Midnight Navy",
        imagem: "Imagens/Produtos/4.png",
        precoDolar: 500,
        marca: "Jordan",
        cor: "Azul Marinho",
        desc: "Com cabedal em couro premium e tons de azul marinho e branco, este Jordan 1 é uma releitura elegante de um dos modelos mais clássicos da marca.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 5,
        nome: "Tênis Tesla Coil Black Blue",
        imagem: "Imagens/Produtos/5.png",
        precoDolar: 58,
        marca: "Tesla",
        cor: "Preto",
        desc: "Modelo moderno com design futurista, o Tesla Coil Black Blue oferece leveza e conforto para o dia a dia, com detalhes em azul que dão um toque esportivo.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 6,
        nome: "Puma Slipstream Mix Bege",
        imagem: "Imagens/Produtos/6.png",
        precoDolar: 110,
        marca: "Puma",
        cor: "Bege",
        desc: "O Puma Slipstream Mix combina materiais de alta qualidade com um visual retrô e tons neutros, ideal para quem busca estilo e conforto em um só tênis.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 7,
        nome: "Puma X-Ray 2 Square Branco",
        imagem: "Imagens/Produtos/7.png",
        precoDolar: 58,
        marca: "Puma",
        cor: "Branco",
        desc: "Com design esportivo e tecnologia de amortecimento, o Puma X-Ray 2 Square é perfeito para o uso diário, oferecendo conforto e estilo urbano.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 8,
        nome: "Vans Knu Skool Navy True White",
        imagem: "Imagens/Produtos/8.png",
        precoDolar: 120,
        marca: "Vans",
        cor: "Azul",
        desc: "Inspirado no estilo skate dos anos 90, o Vans Knu Skool traz cabedal acolchoado e sola vulcanizada, oferecendo conforto e visual retrô autêntico.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 9,
        nome: "Adidas Adi2000 Verde Escuro",
        imagem: "Imagens/Produtos/9.png",
        precoDolar: 160,
        marca: "Adidas",
        cor: "Verde",
        desc: "Um modelo ousado e moderno, o Adi2000 Verde Escuro combina referências dos anos 2000 com conforto e durabilidade típicos da Adidas.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 10,
        nome: "Puma Suede XL Vermelho",
        imagem: "Imagens/Produtos/10.png",
        precoDolar: 180,
        marca: "Puma",
        cor: "Vermelho",
        desc: "Com visual vibrante e acabamento em camurça premium, o Puma Suede XL Vermelho é uma escolha estilosa que se destaca em qualquer look casual.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 11,
        nome: "Superstar Vermelho Azul e Amarelo",
        imagem: "Imagens/Produtos/11.png",
        precoDolar: 70,
        marca: "Superstar",
        cor: "Colorido",
        desc: "O Tênis Superstar ganha uma versão colorida e vibrante, perfeita para quem busca originalidade sem abrir mão do conforto e da tradição.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 12,
        nome: "New Balance 550 Sea Salt Relic Brown",
        imagem: "Imagens/Produtos/12.png",
        precoDolar: 200,
        marca: "New Balance",
        cor: "Branco e Marrom",
        desc: "Com um visual retrô sofisticado, o New Balance 550 combina tons neutros e materiais premium, oferecendo estilo e conforto em um design clássico.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 13,
        nome: "Nike Dunk Low Retro Panda",
        imagem: "Imagens/Produtos/13.png",
        precoDolar: 180,
        marca: "Nike",
        cor: "Branco e Preto",
        desc: "Ícone do streetwear, o Dunk Low Panda apresenta o contraste elegante do preto e branco, combinando com qualquer estilo.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 14,
        nome: "Adidas Campus 00s Marrom",
        imagem: "Imagens/Produtos/14.png",
        precoDolar: 130,
        marca: "Adidas",
        cor: "Marrom",
        desc: "O Adidas Campus 00s traz a nostalgia dos anos 2000 em um modelo moderno, com cabedal em camurça marrom e sola robusta para máximo conforto.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 15,
        nome: "Qix Combat Suede Heart Pack Preto",
        imagem: "Imagens/Produtos/15.png",
        precoDolar: 78,
        marca: "Qix",
        cor: "Preto",
        desc: "Com design robusto e cabedal em camurça, o Qix Combat oferece resistência e estilo urbano, ideal para o skate e o dia a dia.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 16,
        nome: "Nike Air Max 90 Black White",
        imagem: "Imagens/Produtos/16.png",
        precoDolar: 160,
        marca: "Nike",
        cor: "Preto",
        desc: "Clássico e versátil, o Air Max 90 combina conforto, amortecimento Air e design icônico nas cores preto e branco.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 17,
        nome: "Air Jordan Legacy 312 Low Azul",
        imagem: "Imagens/Produtos/17.png",
        precoDolar: 207,
        marca: "Jordan",
        cor: "Branco e Azul",
        desc: "Inspirado em vários modelos clássicos da Jordan, o Legacy 312 Low mistura elementos nostálgicos com um toque moderno e esportivo.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    { 
        id: 18,
        nome: "Air Jordan 1 Low SE Glacier Blue",
        imagem: "Imagens/Produtos/18.png",
        precoDolar: 228,
        marca: "Jordan",
        cor: "Branco e Azul Claro",
        desc: "Com tonalidade suave de azul e branco, o Jordan 1 Low SE Glacier Blue combina elegância e esportividade em um modelo leve e estiloso.",
        tamanhos: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    },
    {
        id: 19,
        nome: "Meia Puma Cano Alto Preto",
        imagem: "Imagens/Produtos/19.png",
        precoDolar: 6,
        marca: "Puma",
        cor: "Preto",
        desc: "Meia confortável e resistente, com cano alto e logo Puma bordado. Ideal para prática esportiva ou uso casual.",
        tamanhos: ["34 - 37", "38 - 42", "43 - 45"],
    },
    { 
        id: 20,
        nome: "Boné Red Bull Racing",
        imagem: "Imagens/Produtos/20.png",
        precoDolar: 14,
        marca: "New Era",
        cor: "Azul Marinho",
        desc: "Boné oficial da equipe Red Bull Racing, com design esportivo, ajuste confortável e logotipo bordado, ideal para fãs de automobilismo.",
        tamanhos: ["Tamanho Único"],
    },
    {
        id: 21,
        nome: "Sholder Bag Mint Blue",
        imagem: "Imagens/Produtos/21.png",
        precoDolar: 10,
        marca: "Tênis Street",
        cor: "Azul Menta",
        desc: "Bolsa tiracolo compacta e moderna, com acabamento em azul menta. Perfeita para levar seus pertences com estilo no dia a dia.",
        tamanhos: ["Tamanho Único"],
    },
    { 
        id: 22,
        nome: "Moletom Preto com Capuz",
        imagem: "Imagens/Produtos/22.png",
        precoDolar: 24,
        marca: "Tênis Street",
        cor: "Preto",
        desc: "Moletom básico com capuz, confeccionado em tecido macio e confortável. Ideal para dias frios e combinações casuais.",
        tamanhos: ["PP", "P", "M", "G", "GG", "EGG"],
    },
    {
        id: 23,
        nome: "Camiseta Bege Estampa Bonsai",
        imagem: "Imagens/Produtos/23.png",
        precoDolar: 12,
        marca: "Tênis Street",
        cor: "Bege",
        desc: "Camiseta leve e estilosa com estampa de bonsai, representando equilíbrio e natureza. Confortável e perfeita para o dia a dia.",
        tamanhos: ["PP", "P", "M", "G", "GG", "EGG"],
    },
    { 
        id: 24,
        nome: "Meia Jordan Cano Alto Branca",
        imagem: "Imagens/Produtos/24.png",
        precoDolar: 6,
        marca: "Jordan",
        cor: "Branco",
        desc: "Meia branca de cano alto com logo da Jordan. Feita em algodão macio, oferece conforto e respirabilidade durante o uso.",
        tamanhos: ["34 - 37", "38 - 42", "43 - 45"],
    },
    {
        id: 25,
        nome: "Boné Simples Preto",
        imagem: "Imagens/Produtos/25.png",
        precoDolar: 10,
        marca: "Tênis Street",
        cor: "Preto",
        desc: "Boné básico e versátil, com aba curva e fechamento ajustável. Um acessório essencial para qualquer look casual.",
        tamanhos: ["Tamanho Único"],
    },
    { 
        id: 26,
        nome: "Camiseta Oversized Preta",
        imagem: "Imagens/Produtos/26.png",
        precoDolar: 16,
        marca: "Tênis Street",
        cor: "Preta",
        desc: "Camiseta preta oversized com caimento solto e tecido leve, ideal para quem busca conforto e estilo streetwear moderno.",
        tamanhos: ["PP", "P", "M", "G", "GG", "EGG"],
    }
];


window.produtos = produtos;
